name: Run shell Commands
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Security folks This is first Github Actions workflow"
